### PR TITLE
5 deactivate daily messages

### PR DESCRIPTION
**Pull request by s-espinosa**
@case-eee Let me know what you think!

# Primary Changes

* Adds 'active' to users table and sets default to true.
* Adds button to the user show to unsubscribe.
* Implements basic authentication/authorization (only allows users to unsubscribe themselves).

# Secondary Changes

* Adds FactoryGirl to `rails_helper`, and factory for users.
* Adds empty home page for redirect if a user is not logged in.

# Questions/Next Steps

* Doesn't actually implement ability to sign in. Seemed like this was separate from activating/deactivating, but let me know if you want me to implement on this PR?
* Currently a user can only see their own show. Does that make sense? I think so, but not sure.

### CODE REVIEW

**Comment by s-espinosa** [comment]
@case-eee Some additional updates:

* Allows users to re-activate their subscriptions.

# Questions

* Currently I'm sending subscribe and unsubscribe both to the update method on a user. This is resulting in some pretty generic flash messages. Will mean that we have the same messages if we update a user. See three potential options: 1) leave as is, 2) send through a conditional of some sort (probably refactored into it's own method, though a PORO feels aggressive), 3) send to separate `controller#action`s where we can have more specific messages. Thoughts?
* Not sure if I like the organization of these tests, but wanted to check to see what you thought. Put them all in one? Split into more specific functionality?

Let me know what you think!

**Comment by case-eee** [comment]
@s-espinosa 

- i think the organization of your tests looks fine to me!
- as far as the generic flash messages go - maybe we leave it like this for now and then we make a card to handle it later? i think it'd be nice to have more specific messages but i don't think it's essential
- we'll also need to move where the TwilioMessage is sent eventually. i guess it won't be sent anywhere really - it will just be automatic. it may be nice to have a welcome message of some sort upon a user signing up or even a message saying that they've deactivated their account? what do you think about that? is that too much?

**Comment by s-espinosa** [comment]
@case-eee 

* re: tests - sounds good!
* re: generic flash messages/Twilio messages - I started to work down the path of sending messages when they subscribe and realized it was pretty tightly coupled with the flash messages, so I went ahead and implemented both. Currently it's in a private method on the UsersController. This feels like I'm fattening that controller a little bit, but absent some more additions that felt more straightforward than a PORO to achieve the same objective. Let me know if you disagree or think there's another way we could handle. 👍 

Other related changes:

* I made some slight adjustments to the phone numbers in the test, so that should run. Going to go ahead and close the other PR since this now incorporates that change.
* I added a sample `application.yml` file. This is consistent with how I have mine set up, and gives us a place to store the "to:" number that Twilio wants for passing specs.

Let me know what you think!

**Review by case-eee — APPROVED** [review]
this looks wonderful @s-espinosa 👍

**Pull request merged**
